[package]
name = "sudoku"
version = "0.1.0"
authors = ["paddywwoof <patrick@eldwick.org.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
